/**:
  ros__parameters:
    desired_torso_pitch: 180.0
    controller: 1
    kp: 0.75
    ki: 0.0
    kd: 0.08
    wheel_max_torque: 9.0
    control_max_integral: 5.0
    log_data: true
    define_log_name: false
    log_name: testing
trial_values:
  torso_pitch_init: 3.0970134735107422
  wheel_rel_pos_init: -0.00076699041528627276