/**:
  ros__parameters:
    desired_torso_pitch: 210.0
    controller: 1
    kp: 0.75
    ki: 0.0
    kd: 0.08
    wheel_max_torque: 9.0
    control_max_integral: 5.0
    log_data: true
    define_log_name: false
    log_name: testing
trial_values:
  torso_pitch_init: 3.135944128036499
  mot_pos_init: -21.507465362548828