/**:
  ros__parameters:
  # all parameters must be floats
    desired_torso_pitch: 90.0 #degrees
    controller: 0 # 1 for PID or 1 for PDGC (PD + Gravity compensation)
    kp: 0.65
    ki: 0.05
    kd: 0.08
    wheel_max_torque: 9.0 # at the wheel;
    control_max_integral: 4.0
    log_data: true # true for logging data and false for not
    define_log_name: false
    log_name: "testing"
