/**:
  ros__parameters:
  # all parameters must be floats
    desired_torso_pitch: 90.0 #degrees
    kp: 0.65
    ki: 0.0
    kd: 0.08
    wheel_max_torque: 7.0 # at the wheel
    control_max_integral: 4.0
    log_data: true # y for logging data and n for not
