/**:
  ros__parameters:
    desired_torso_pitch: 90.0
    controller: 1
    kp: 0.75
    ki: 0.025
    kd: 0.08
    wheel_max_torque: 9.0
    control_max_integral: 4.0
    log_data: true
    define_log_name: false
    log_name: testing
trial_values:
  torso_pitch_init: 3.1260836124420166
  mot_pos_init: 93.665061950683594